#!/bin/sh
set -e
# Automatically added by dh_installsystemd/14.3
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'blankresd.service' >/dev/null || true
fi
# End automatically added section
